version: 2
updates:
  - package-ecosystem: pip
    directory: "/AI Resume Classifier (NLP + ML)"
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: "/AI Resume Classifier (NLP + ML)"
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }
